const SCREEN = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  USER_SCREEN: 'USER_SCREEN',
  CATEGORY_SCREEN: 'CATEGORY_SCREEN',
  SUGGEST_SCREEN: 'SUGGEST_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  CATEGORY_DETAIL_SCREEN: 'CATEGORY_DETAIL_SCREEN',
  DETAIL_PRODUCT_SCREEN: 'DETAIL_PRODUCT',
  STORAGE_USER_SCREEN: 'STORAGE_USER_SCREEN',
  FOOD_DETAIL_SCREEN: 'FOOD_DETAIL_SCREEN',
};

export default SCREEN;
